
// 
export const TOGGLE_IS_ADDING = "TOGGLE_IS_ADDING";

export const FILTER_SHOW_ALL = 'FILTER_SHOW_ALL';
export const FILTER_MEMORIZED = 'FILTER_MEMORIZED';
export const FILTER_NEED_PRACTICE = 'FILTER_NEED_PRACTICE';

export const ADD_WORD = 'ADD_WORD';
export const ADD_WORD_SUCCESS = 'ADD_WORD_SUCCESS';
export const TOGGLE_SHOW = 'TOGGLE_SHOW';
export const TOGGLE_MEMORIZED = 'TOGGLE_MEMORIZED'
